package com.namonamo.app.constant;

import java.util.Hashtable;

public class NamoNamoConstant {
	public static String DEVICE_ID = "123456";
	public static final String X_APPKEY = "jludmkiswzxmrdf3qewfuhasqrcmdjoqply";
	public static final String GENRAL_GROUP = "NAMONAMO_GENRAL";

	public static final String UPLOAD_IMAGE_DIR = "file:///mnt/sdcard/NamoNamo/Upload/NamoNamo Image/";
	public static final String MEDIA_IMAGE_DIR = "file:///mnt/sdcard/NamoNamo/Media/NamoNamo Image/";
	public static final String SendMessageUrl = "http://info.rcgemini.in/submitsms.jsp?user=HHELLO&key=e0dc9f8da1XX&mobile=+919467298066&message=test%20sms&senderid=HHELLO&accusage=1";

	// public static final String BASE_URL =
	// "http://85.25.203.12/chatproject.php/api/user/";
	public static final String BASE_URL = "http://hihelloapp.com/index.php/api/user/";
	public static final String UPLOAD_PIC_URL = BASE_URL + "uploadPhoto";
	public static final String RegistrationUrl = BASE_URL + "registration";
	public static final String GetTopTenDailyReward = BASE_URL
			+ "getTopTenDailyReward";
	public static final String GetDailyMessageUrl = BASE_URL
	+ "getDailyMessage";
	public static final String GetCMSUrl = "http://namonamoapp.com/api/forceupgrade/cms.json";

	public static String GetUserDetail = BASE_URL + "getUserDetail";
	public static String GetTopTenReward = BASE_URL + "getTopTenReward";
	public static String GetTopTenContactReward = BASE_URL
			+ "getTopTenContactReward";
	public static String GetUserRewardUrl = BASE_URL + "getUserReward";
	public static String AddRewardUrl = BASE_URL + "addReward";
	public static final String SendInvitationUrl = BASE_URL + "sendInvitation";
	
	public static String GetUserByJidUrl = BASE_URL + "getUserDetailByJid";
	public static String UpdateProfileUrl = BASE_URL + "updateUsersProfile";
	public static String UploadMediaUrl = BASE_URL + "uploadMedia";
	public static String DeleteBlockUserUrl = BASE_URL + "deleteBlockUser";
	public static String BlockUserUrl = BASE_URL + "blockUser";
	public static String GetBlockUserUrl = BASE_URL + "getBlockJids";

	public static Hashtable<String, String> getAllCountryCode() {
		Hashtable<String, String> countryISDCodes = new Hashtable<String, String>(
				300);
		countryISDCodes.put("Afghanistan",  "+93");
		countryISDCodes.put("Albania",      "+355");
		countryISDCodes.put("Algeria",      "+213");
		countryISDCodes.put("American Samoa","+1684");
		countryISDCodes.put("Andorra", "+376");
		countryISDCodes.put("Angola", "+244");
		countryISDCodes.put("Anguilla", "+1264");
		countryISDCodes.put("Antarctica", "+672");
		countryISDCodes.put("Antigua and Barbuda", "+1268");
		countryISDCodes.put("Argentina", "+54");
		countryISDCodes.put("Armenia", "+374");
		countryISDCodes.put("Aruba", "+297");
		countryISDCodes.put("Australia", "+61");
		countryISDCodes.put("Austria", "+43");
		countryISDCodes.put("Azerbaijan", "+994");
		countryISDCodes.put("Bahamas", "+1242");
		countryISDCodes.put("Bahrain", "+973");
		countryISDCodes.put("Bangladesh", "+880");
		countryISDCodes.put("Barbados", "+1246");
		countryISDCodes.put("Belarus", "+375");
		countryISDCodes.put("Belgium", "+32");
		countryISDCodes.put("Belize", "+501");
		countryISDCodes.put("Benin", "+229");
		countryISDCodes.put("Bermuda", "+1441");
		countryISDCodes.put("Bhutan", "+975");
		countryISDCodes.put("Bolivia", "+591");
		countryISDCodes.put("Bosnia and Herzegovina", "+387");
		countryISDCodes.put("Botswana", "+267");
		countryISDCodes.put("Brazil", "+55");
		countryISDCodes.put("British Virgin Islands", "+1284");
		countryISDCodes.put("Brunei", "+673");
		countryISDCodes.put("Bulgaria", "+359");
		countryISDCodes.put("Burkina Faso", "+226");
		countryISDCodes.put("Burma (Myanmar)", "+95");
		countryISDCodes.put("Burundi", "+257");
		countryISDCodes.put("Cambodia", "+855");
		countryISDCodes.put("Cameroon", "+237");
		countryISDCodes.put("Canada", "+1");
		countryISDCodes.put("Cape Verde", "+238");
		countryISDCodes.put("Cayman Islands", "+1345");
		countryISDCodes.put("Central African Republic", "+236");
		countryISDCodes.put("Chad", "+235");
		countryISDCodes.put("Chile", "+56");
		countryISDCodes.put("China", "+86");
		countryISDCodes.put("Christmas Island", "+61");
		countryISDCodes.put("Cocos Islands", "+61");
		countryISDCodes.put("Colombia", "+57");
		countryISDCodes.put("Comoros", "+269");
		countryISDCodes.put("Cook Islands", "+682");
		countryISDCodes.put("Costa Rica", "+506");
		countryISDCodes.put("Croatia", "+385");
		countryISDCodes.put("Cuba", "+53");
		countryISDCodes.put("Cyprus", "+357");
		countryISDCodes.put("Czech Republic", "+420");
		countryISDCodes.put("Congo", "+243");
		countryISDCodes.put("Denmark", "+45");
		countryISDCodes.put("Djibouti", "+253");
		countryISDCodes.put("Dominica", "+1767");
		countryISDCodes.put("Dominican Republic", "+1809");
		countryISDCodes.put("Ecuador", "+593");
		countryISDCodes.put("Egypt", "+20");
		countryISDCodes.put("El Salvador", "+503");
		countryISDCodes.put("Equatorial Guinea", "+240");
		countryISDCodes.put("Eritrea", "+291");
		countryISDCodes.put("Estonia", "+372");
		countryISDCodes.put("Ethiopia", "+251");
		countryISDCodes.put("Falkland Islands", "+500");
		countryISDCodes.put("Faroe Islands", "+298");
		countryISDCodes.put("Fiji", "+679");
		countryISDCodes.put("Finland", "+358");
		countryISDCodes.put("France", "+33");
		countryISDCodes.put("French Polynesia", "+689");
		countryISDCodes.put("Gabon", "+241");
		countryISDCodes.put("Gambia", "+220");
		countryISDCodes.put("Gaza Strip", "+970");
		countryISDCodes.put("Georgia", "+995");
		countryISDCodes.put("Germany", "+49");
		countryISDCodes.put("Ghana", "+233");
		countryISDCodes.put("Gibraltar", "+350");
		countryISDCodes.put("Greece", "+30");
		countryISDCodes.put("Greenland", "+299");
		countryISDCodes.put("Grenada", "+1473");
		countryISDCodes.put("Guam", "+1671");
		countryISDCodes.put("Guatemala", "+502");
		countryISDCodes.put("Guinea", "+224");
		countryISDCodes.put("Guinea-Bissau", "+245");
		countryISDCodes.put("Guyana", "+592");
		countryISDCodes.put("Haiti", "+509");
		countryISDCodes.put("Holy See (Vatican City)", "+39");
		countryISDCodes.put("Honduras", "+504");
		countryISDCodes.put("Hong Kong", "+852");
		countryISDCodes.put("Hungary", "+36");
		countryISDCodes.put("Iceland", "+354");
		countryISDCodes.put("India", "+91");
		countryISDCodes.put("Indonesia", "+62");
		countryISDCodes.put("Iran", "+98");
		countryISDCodes.put("Iraq", "+964");
		countryISDCodes.put("Ireland", "+353");
		countryISDCodes.put("Isle of Man", "+44");
		countryISDCodes.put("Israel", "+972");
		countryISDCodes.put("Italy", "+39");
		countryISDCodes.put("Ivory Coast", "+225");
		countryISDCodes.put("Jamaica", "+1876");
		countryISDCodes.put("Japan", "+81");
		countryISDCodes.put("Jordan", "+962");
		countryISDCodes.put("Kazakhstan", "+7");
		countryISDCodes.put("Kenya", "+254");
		countryISDCodes.put("Kiribati", "+686");
		countryISDCodes.put("Kosovo", "+381");
		countryISDCodes.put("Kuwait", "+965");
		countryISDCodes.put("Kyrgyzstan", "+996");
		countryISDCodes.put("Laos", "+856");
		countryISDCodes.put("Latvia", "+371");
		countryISDCodes.put("Lebanon", "+961");
		countryISDCodes.put("Lesotho", "+266");
		countryISDCodes.put("Liberia", "+231");
		countryISDCodes.put("Libya", "+218");
		countryISDCodes.put("Liechtenstein", "+423");
		countryISDCodes.put("Lithuania", "+370");
		countryISDCodes.put("Luxembourg", "+352");
		countryISDCodes.put("Macau", "+853");
		countryISDCodes.put("Macedonia", "+389");
		countryISDCodes.put("Madagascar", "+261");
		countryISDCodes.put("Malawi", "+265");
		countryISDCodes.put("Malaysia", "+60");
		countryISDCodes.put("Maldives", "+960");
		countryISDCodes.put("Mali", "+223");
		countryISDCodes.put("Malta", "+356");
		countryISDCodes.put("Marshall Islands", "+692");
		countryISDCodes.put("Mauritania", "+222");
		countryISDCodes.put("Mauritius", "+230");
		countryISDCodes.put("Mayotte", "+262");
		countryISDCodes.put("Mexico", "+52");
		countryISDCodes.put("Micronesia", "+691");
		countryISDCodes.put("Moldova", "+373");
		countryISDCodes.put("Monaco", "+377");
		countryISDCodes.put("Mongolia", "+976");
		countryISDCodes.put("Montenegro", "+382");
		countryISDCodes.put("Montserrat", "+1664");
		countryISDCodes.put("Morocco", "+212");
		countryISDCodes.put("Mozambique", "+258");
		countryISDCodes.put("Namibia", "+264");
		countryISDCodes.put("Nauru", "+674");
		countryISDCodes.put("Nepal", "+977");
		countryISDCodes.put("Netherlands", "+31");
		countryISDCodes.put("Netherlands Antilles", "+599");
		countryISDCodes.put("New Caledonia", "+687");
		countryISDCodes.put("New Zealand", "+64");
		countryISDCodes.put("Nicaragua", "+505");
		countryISDCodes.put("Niger", "+227");
		countryISDCodes.put("Nigeria", "+234");
		countryISDCodes.put("Niue", "+683");
		countryISDCodes.put("Norfolk Island", "+672");
		countryISDCodes.put("North Korea", "+850");
		countryISDCodes.put("Northern Mariana Islands", "+1670");
		countryISDCodes.put("Norway", "+47");
		countryISDCodes.put("Oman", "+968");
		countryISDCodes.put("Pakistan", "+92");
		countryISDCodes.put("Palau", "+680");
		countryISDCodes.put("Panama", "+507");
		countryISDCodes.put("Papua New Guinea", "+675");
		countryISDCodes.put("Paraguay", "+595");
		countryISDCodes.put("Peru", "+51");
		countryISDCodes.put("Philippines", "+63");
		countryISDCodes.put("Pitcairn Islands", "+870");
		countryISDCodes.put("Poland", "+48");
		countryISDCodes.put("Portugal", "+351");
		countryISDCodes.put("Puerto Rico", "+1");
		countryISDCodes.put("Qatar", "+974");
		countryISDCodes.put("Republic of the Congo", "+242");
		countryISDCodes.put("Romania", "+40");
		countryISDCodes.put("Russia", "+7");
		countryISDCodes.put("Rwanda", "+250");
		countryISDCodes.put("Saint Barthelemy", "+590");
		countryISDCodes.put("Saint Helena", "+290");
		countryISDCodes.put("Saint Kitts and Nevis", "+1869");
		countryISDCodes.put("Saint Lucia", "+1758");
		countryISDCodes.put("Saint Martin", "+1599");
		countryISDCodes.put("Saint Pierre and Miquelon", "+508");
		countryISDCodes.put("Saint Vincent and the Grenadines", "+1784");
		countryISDCodes.put("Samoa", "+685");
		countryISDCodes.put("San Marino", "+378");
		countryISDCodes.put("Sao Tome and Principe", "+239");
		countryISDCodes.put("Saudi Arabia", "+966");
		countryISDCodes.put("Senegal", "+221");
		countryISDCodes.put("Serbia", "+381");
		countryISDCodes.put("Seychelles", "+248");
		countryISDCodes.put("Sierra Leone", "+232");
		countryISDCodes.put("Singapore", "+65");
		countryISDCodes.put("Slovakia", "+421");
		countryISDCodes.put("Slovenia", "+386");
		countryISDCodes.put("Solomon Islands", "+677");
		countryISDCodes.put("Somalia", "+252");
		countryISDCodes.put("South Africa", "+27");
		countryISDCodes.put("South Korea", "+82");
		countryISDCodes.put("Spain", "+34");
		countryISDCodes.put("Sri Lanka", "+94");
		countryISDCodes.put("Sudan", "+249");
		countryISDCodes.put("Suriname", "+597");
		countryISDCodes.put("Swaziland", "+268");
		countryISDCodes.put("Sweden", "+46");
		countryISDCodes.put("Switzerland", "+41");
		countryISDCodes.put("Syria", "+963");
		countryISDCodes.put("Taiwan", "+886");
		countryISDCodes.put("Tajikistan", "+992");
		countryISDCodes.put("Tanzania", "+255");
		countryISDCodes.put("Thailand", "+66");
		countryISDCodes.put("Timor-Leste", "+670");
		countryISDCodes.put("Togo", "+228");
		countryISDCodes.put("Tokelau", "+690");
		countryISDCodes.put("Tonga", "+676");
		countryISDCodes.put("Trinidad and Tobago", "+1868");
		countryISDCodes.put("Tunisia", "+216");
		countryISDCodes.put("Turkey", "+90");
		countryISDCodes.put("Turkmenistan", "+993");
		countryISDCodes.put("Turks and Caicos Islands", "+1649");
		countryISDCodes.put("Tuvalu", "+688");
		countryISDCodes.put("Uganda", "+256");
		countryISDCodes.put("Ukraine", "+380");
		countryISDCodes.put("United Arab Emirates", "+971");
		countryISDCodes.put("United Kingdom", "+44");
		countryISDCodes.put("United States", "+1");
		countryISDCodes.put("Uruguay", "+598");
		countryISDCodes.put("US Virgin Islands", "+1340");
		countryISDCodes.put("Uzbekistan", "+998");
		countryISDCodes.put("Vanuatu", "+678");
		countryISDCodes.put("Venezuela", "+58");
		countryISDCodes.put("Vietnam", "+84");
		countryISDCodes.put("Wallis and Futuna", "+681");
		countryISDCodes.put("West Bank", "+970");
		countryISDCodes.put("Yemen", "+967");
		countryISDCodes.put("Zambia", "+260");
		countryISDCodes.put("Zimbabwe", "+263");
		return countryISDCodes;
	}

}
